version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: nico-openclaw_server_1
      APP_PORT: 18789
    container_name: nico-openclaw_app_proxy_1
  server:
    image: ghcr.io/xyse/openclaw:latest
    user: root
    restart: on-failure
    stop_grace_period: 1m
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_CONFIG_DIR: /home/node/.openclaw
      OPENCLAW_WORKSPACE_DIR: /home/node/clawd
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN:-openclaw}
    volumes:
      - ${APP_DATA_DIR}/data/openclaw:/home/node/.openclaw
      - ${APP_DATA_DIR}/data/workspace:/home/node/clawd
    working_dir: /app
    init: true
    command:
      - node
      - dist/index.js
      - gateway
      - '--allow-unconfigured'
      - '--bind'
      - lan
      - '--port'
      - '18789'
    container_name: nico-openclaw_server_1
